language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r test_requirements.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=templating
after_success:
  coveralls
